name: file-nexus-prod
services:
  broker:
    image: apache/kafka:latest
    container_name: broker
    mem_limit: 512m
    ports:
      - "29092:29092"
    volumes:
      - ~/projects/containers/volumes/kafka_data:/var/lib/kafka/data
    networks:
      - kafka-net
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://broker:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,EXTERNAL://localhost:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    mem_limit: 512m
    depends_on:
      - broker
      - connect
    ports:
      - 9090:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:9092
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: connect
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://connect:8083
      DYNAMIC_CONFIG_ENABLED: 'true'
    #    volumes:
    #      - ./kui/config.yml:/etc/kafkaui/dynamic_config.yaml
    networks:
      - kafka-net
    restart: unless-stopped

  connect:
    image: confluentinc/cp-kafka-connect:latest
    mem_limit: 1024m
    depends_on:
      - broker
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: broker:9092
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_GROUP_ID: "filepulse-connect-cluster"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-statuses"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_PLUGIN_PATH: "/usr/share/java"
    volumes:
      - ~/projects/containers/volumes/kafka-connect/plugins/file-pulse/lib:/usr/share/java/filepulse
      - ~/projects/containers/volumes/kafka-connect/connect:/connect
    networks:
      - kafka-net
    restart: unless-stopped

  file-nexus:
    container_name: file-nexus
    mem_limit: 512m
    image: thatssatyadocker/file-nexus:latest
    ports:
      - 8080:8080
    env_file:
      - .env
    restart: unless-stopped

networks:
  kafka-net:
    driver: bridge